// Source: https://www.fanfare.design/expositions
// Retrieved 2026-10-07. Titles and venues are preserved from the artist page.

export const personalExhibitions = [
  "2016 — Triptyque — Centre Culturel de l’Eden, Charleroi, Belgique",
  "2014 — Patrick Everaert - Evermore — Espace 251 Nord, Liège, Belgique",
  "2011 — Patrick Everaert — Artothèque, Angers",
  "2010 — Patrick Everaert - Black Soil Power Project — Galerie Aline Vidal, Paris, France",
  "2009 — Patrick Everaert — Galerie Meessen - De Clercq, Bruxelles, Belgique",
  "2007 — Patrick Everaert — Galerie Aline Vidal, Paris, France",
  "2006 — 42x60 affichage dans les rues de Paris — Divers lieux, Paris",
  "2005 — Patrick Everaert — Galerie Aline Vidal, Paris, France",
  "2005 — Patrick Everaert — EROA Hergé, Gondecourt, France",
  "2004 — Patrick Everaert — Frac Provence-Alpes-Côte d'Azur, Marseille, France",
  "2003 — Patrick Everaert — Galerie Aline Vidal, Paris, France",
  "2002 — Patrick Everaert - Tuer le Temps — BPS22 Centre d’Art Contemporain, Charleroi, Belgique",
  "2000 — Patrick Everaert — Centre d’art Chapelle de Boendael, Bruxelles, Belgique",
  "1998 — Patrick Everaert — Galerie Brownstone, Correard & cie, Paris, France",
  "1995 — Patrick Everaert — Galerie Météo, Paris, France",
  "1995 — Patrick Everaert — Galerie Etienne Tilman, Bruxelles, Belgique",
  "1994 — Patrick Everaert — Château de Vitré, France",
  "1993 — Patrick Everaert — Galerie Météo, Paris, France",
  "1992 — Patrick Everaert — Etablissements d’en face, Bruxelles, Belgique",
] as const;

export const collectiveExhibitions = [
  "2021 — Magma - 10ème Triennale d’Art Contemporain — Musée L, Louvain La Neuve et Centre Culturel, Ottignies, Belgique",
  "2019 — Comme un souffle — Galerie Ravaisou, Bandol, France",
  "2018 — De(S)Rives - Parcours artistique sur l’île Saint-Louis — Galerie Aline Vidal, Paris, France",
  "2018 — Moi, je…!? - Autoportrait en questions — BPS22, Charleroi, Belgique",
  "2017 — Robert Doisneau, Patrick Everaert - Regards croisés d'artistes sur le Palais de la Découverte — Palais de la découverte, Paris, France",
  "2017 — Triennale Art Public — Place Verte, Charleroi, Belgique",
  "2016 — My best off, et vous ? — Galerie Mobile Aline Vidal, Paris, France",
  "2016 — Uchronies — BPS22, Charleroi, Belgique",
  "2016 — Fantômes et apparitions — Château du Rivau, Le Coudray, France",
  "2015 — Chimera — Meet Factory, Prague, République tchèque",
  "2015 — Lens na Spinoza — Croxhapox, Gent, Belgique",
  "2014 — Verf na Van Eyck — Croxhapox, Gent, Belgique",
  "2014 — Il n'y a pas de monde achevé — École nationale supérieure de la photographie, Arles, France",
  "2014 — Le mur - œuvres de la collection Antoine de Galbert — La Maison Rouge, Paris, France",
  "2014 — One Shot! — Museo brasileiro da escultura, Sao Paulo, Brésil",
  "2013 — Métamorphose(s) 1883-2013 – Entropia — Centre d'art Walter Benjamin, Perpignan, France",
  "2012 — L'Institut des Archives Sauvages — Villa Arson, Nice, France",
  "2011 — PACS Galerie Aline Vidal / Tools Galerie — Galerie Aline Vidal, Paris, France",
  "2011 — La Vie Mode d’Emploi (Life A user’s Manual) — Galerie Meessen - De Clercq, Bruxelles, Belgique",
  "2010 — The State of Things — National Art Museum of China, Pekin, Chine",
  "2010 — One Shot! — BPS22, Charleroi, Belgique",
  "2010 — Green Summer — Verbeke Foundation, Kemzeke, Belgique",
  "2010 — Objects are like they appears — Galerie Meessen - De Clercq, Bruxelles, Belgique",
  "2010 — Manière Noire — BAM, Mons, Belgique",
  "2009 — The State of Things — Palais des Beaux Arts, Bruxelles, Belgique",
  "2009 — How to change your life in a day — Galerie Aline Vidal, Paris, France",
  "2009 — La Galerie Aline Vidal s’expose à Izmir — Centre Culturel Français D’Izmir, Turquie",
  "2009 — La galerie Aline Vidal s’expose à Marseille — Galerie des bains douches de la plaine, Marseille, France",
  "2008 — The IKOB collection — Museum van Bommel van Dam, Venlo, Pays-Bas",
  "2008 — Les sujets en moins — Galerie Léo Scheer, Paris, France",
  "2007 — Nieuwe Collectie — Stedelijk Museum Wuyts-Va Campen & Baron Caroly, Lier, Belgique",
  "2007 — L’habit ne fait pas... — E.S.P.A.C.E. Peiresc, Toulon, France",
  "2007 — Best of — Galerie Aline Vidal, Paris, France",
  "2006 — Tunnel Vision — Fotomuseum, Anvers, Belgique",
  "2006 — Portrait d'une collection: IDEA — Musée de la Photographie, Charleroi, Belgique",
  "2006 — Partenaire Particulier — FRAC paca, Marseille, France",
  "2006 — Sciences Fictions — Galerie Aline Vidal, Paris, France",
  "2005 — Brussels South Airport — Krinzinger Project, Vienne, Autriche",
  "2005 — Lotissement de cimaises — Centre d’art de la Villa Arson, Nice, France",
  "2005 — Faire Signe — La Criée, Centre d’art contemporain, Rennes, France",
  "2005 — Vingt Ans Après - Un Atelier Imaginaire — CWAC, Flémalle, Belgique",
  "2005 — Artothèque 2005, les acquisitions — Nouveau théâtre d’Angers, Angers, France",
  "2004 — Eblouissement — Galerie Nationale du Jeu de Paume, Paris",
  "2004 — One Man Show — Art Brussels, Galerie Aline Vidal, Bruxelles",
  "2003 — Le beau corps de la mémoire — MAC'S, Musée d’Art Contemporain du Grand-Hornu, Belgique",
  "2003 — Images au centre — Château de Tours, France",
  "2002 — Le colloque des chiens — Espace 251 Nord, Liège, Belgique",
  "2002 — De la recherche à l'humain — Château de Seneffe, Belgique",
  "2002 — Human-Isme — Orion Art Gallery, Oostende, Belgique",
  "2001 — Positionen der peripherie - Sammlung der Provinz Hennegau — IKOB, Eupen, Belgique",
  "2001 — Marianne Berenhaut, Goele De Bruyn, Patrick Everaert, Lukas Vandenabeele — Galerie Nadja Vilenne, Liège, Belgique",
  "2001 — La trahison des images / Portraits de scènes — 49e Biennale de Venise - Palazzo Franchetti, Italie",
  "2001 — Ici et Maintenant — Entrepôt Royal Tour & Taxis, Bruxelles, Belgique",
  "2000 — Quand soufflent les vents du sud — Banque Bruxelles Lambert et Musée d’art wallon, Liège, Belgique",
  "2000 — Quand soufflent les vents du sud — Tallin, Estonie",
  "1999 — Radicalité dire les qualités — Galerie Brownstone, Correard & cie, Paris, France",
  "1998 — Biennale de l'image — Centre National de la Photographie, Paris, France",
  "1998 — Enfermement photographique — Maison Européenne de la Photographie, Paris, France",
  "1997 — Météo-Show — Galerie Météo, Paris, France",
  "1997 — Ami, entends-tu? — Galerie Météo, Paris, France",
  "1997 — Objectif lune — Centre d’Art de Neuchâtel, Suisse",
  "1997 — Uit het ongewisse (Entre chien et loup) — Koninklijk Museum voor Schone Kunsten - ICC, Antwerpen, Belgique",
  "1996 — Non! pas comme ça! — Centre d’Art de Neuchâtel, Suisse",
  "1994 — 60 rooms with a view — Hilton, Amsterdam, Pays-Bas",
  "1994 — The drawing room — The drawing room, Amsterdam, Pays-Bas",
  "1994 — Les choix de Bruxelles — Anciennes Usines Jacqmotte, Bruxelles, Belgique",
  "1992 — Jeune Peinture Belge — Palais des Beaux-arts, Bruxelles, Belgique",
  "1992 — Via Farini — Associazione per la promozione della ricerca artistica, Milano, Italie",
  "1992 — Le triomphe de la peinture — Galerie Météo, Paris, France",
] as const;
